spring.application.name=AIT-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.jwt.cookie-name=jwt
app.security.jwt.cookie-max-age-seconds=86400
app.security.jwt.cookie-secure=true
app.security.jwt.cookie-same-site=Lax

cheapshark.api.base-url=https://www.cheapshark.com/api/1.0
cheapshark.redirect.base-url=https://www.cheapshark.com
cheapshark.cache.deals.ttl-seconds=3600
cheapshark.cache.deals.scheduler.store-ids=1,7,25
rawg.api.base-url=https://api.rawg.io/api
rawg.api.key=${RAWG_TOKEN:}

spring.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DB}?authSource=admin

spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME:b55a1320423516}
spring.mail.password=${MAIL_PASSWORD:1c109c3552a26b}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

notifications.wishlist-on-sale.from=${MAIL_FROM:no-reply@ait.local}
notifications.wishlist-on-sale.scheduler-delay-ms=86400000

notifications.daily-digest.from=${MAIL_FROM:no-reply@ait.local}
notifications.daily-digest.scheduler-delay-ms=86400000

